# Generated by Django 5.1.14 on 2025-12-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provideraccount",
            name="incoterms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provideraccount",
            name="kunnr_rg",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="provideraccount",
            name="kunnr_za",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="provideraccount",
            name="pin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="provideraccount",
            name="program",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="provideraccount",
            name="vbeln",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="provideraccount",
            name="vkorg",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
