# Generated by Django 5.1.14 on 2025-11-30 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("search", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_pin_a9174b_idx",
            old_name="products_p_pin_ab1b65_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_brand_4bfaa4_idx",
            old_name="products_p_brand_d1b85b_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_source_166a53_idx",
            old_name="products_p_source__9006b7_idx",
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="product",
            name="search_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="search.searchrequest",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("search_request", "artid")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["user"], name="products_pr_user_id_c7a680_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["search_request"], name="products_pr_search__e79c9d_idx"
            ),
        ),
    ]
