# Generated by Django 5.1.14 on 2025-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_armtek_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="alt_articles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="inner_diameter_mm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="manufacturer_part_number",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="material",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="oem_number",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="package_height_mm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="package_length_mm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="package_weight_g",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="package_width_mm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="product_weight_g",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
