# Generated by Django 5.1.14 on 2025-12-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_alt_articles_product_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="oem_number_primary",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
